# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'niosh.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nioshDialog(object):
    def setupUi(self, nioshDialog):
        nioshDialog.setObjectName("nioshDialog")
        nioshDialog.resize(351, 404)
        nioshDialog.setAcceptDrops(False)
        nioshDialog.setAutoFillBackground(False)
        nioshDialog.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: #fff;")
        nioshDialog.setSizeGripEnabled(False)
        nioshDialog.setModal(False)
        self.weightLabel = QtWidgets.QLabel(nioshDialog)
        self.weightLabel.setGeometry(QtCore.QRect(70, 40, 91, 20))
        self.weightLabel.setObjectName("weightLabel")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(nioshDialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(170, 30, 121, 31))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.distanceLabel = QtWidgets.QLabel(nioshDialog)
        self.distanceLabel.setGeometry(QtCore.QRect(60, 90, 91, 20))
        self.distanceLabel.setObjectName("distanceLabel")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(nioshDialog)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(170, 80, 121, 31))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gripLabel = QtWidgets.QLabel(nioshDialog)
        self.gripLabel.setGeometry(QtCore.QRect(80, 240, 71, 16))
        self.gripLabel.setObjectName("gripLabel")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(nioshDialog)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(170, 130, 121, 31))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.hDistance = QtWidgets.QLabel(nioshDialog)
        self.hDistance.setGeometry(QtCore.QRect(40, 140, 111, 20))
        self.hDistance.setObjectName("hDistance")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(nioshDialog)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(170, 180, 121, 31))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.vDistance = QtWidgets.QLabel(nioshDialog)
        self.vDistance.setGeometry(QtCore.QRect(50, 190, 101, 20))
        self.vDistance.setObjectName("vDistance")
        self.calcButton = QtWidgets.QPushButton(nioshDialog)
        self.calcButton.setGeometry(QtCore.QRect(70, 360, 100, 30))
        self.calcButton.setStyleSheet("background-color: white; color: black;")
        self.calcButton.setObjectName("calcButton")
        self.calcButton_2 = QtWidgets.QPushButton(nioshDialog)
        self.calcButton_2.setGeometry(QtCore.QRect(180, 360, 100, 30))
        self.calcButton_2.setStyleSheet("background-color: white; color: black;")
        self.calcButton_2.setObjectName("calcButton_2")
        self.gripBox = QtWidgets.QComboBox(nioshDialog)
        self.gripBox.setGeometry(QtCore.QRect(170, 230, 121, 31))
        self.gripBox.setMinimumContentsLength(3)
        self.gripBox.setObjectName("gripBox")
        self.gripBox.addItem("")
        self.gripBox.addItem("")
        self.gripBox.addItem("")

        self.retranslateUi(nioshDialog)
        QtCore.QMetaObject.connectSlotsByName(nioshDialog)

    def retranslateUi(self, nioshDialog):
        _translate = QtCore.QCoreApplication.translate
        nioshDialog.setWindowTitle(_translate("nioshDialog", "NIOSH Calculator"))
        self.weightLabel.setText(_translate("nioshDialog", "Object Weight"))
        self.distanceLabel.setText(_translate("nioshDialog", "Object Distance"))
        self.gripLabel.setText(_translate("nioshDialog", "Grip Quality"))
        self.hDistance.setText(_translate("nioshDialog", "Horizontal Distance"))
        self.vDistance.setText(_translate("nioshDialog", "Vertical Distance"))
        self.calcButton.setText(_translate("nioshDialog", "Calculate"))
        self.calcButton_2.setText(_translate("nioshDialog", "Clear"))
        self.gripBox.setItemText(0, _translate("nioshDialog", "Good"))
        self.gripBox.setItemText(1, _translate("nioshDialog", "Fair"))
        self.gripBox.setItemText(2, _translate("nioshDialog", "Bad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nioshDialog = QtWidgets.QDialog()
    ui = Ui_nioshDialog()
    ui.setupUi(nioshDialog)
    nioshDialog.show()
    sys.exit(app.exec_())
