# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'niosh.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nioshDialog(object):
    def setupUi(self, nioshDialog):
        nioshDialog.setObjectName("nioshDialog")
        nioshDialog.resize(380, 409)
        nioshDialog.setAcceptDrops(False)
        nioshDialog.setAutoFillBackground(False)
        nioshDialog.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: #fff;")
        nioshDialog.setSizeGripEnabled(False)
        nioshDialog.setModal(False)
        self.calcButton = QtWidgets.QPushButton(nioshDialog)
        self.calcButton.setGeometry(QtCore.QRect(130, 370, 101, 30))
        self.calcButton.setStyleSheet("background-color: white;\n"
"color: black;")
        self.calcButton.setObjectName("calcButton")
        self.calcButton_2 = QtWidgets.QPushButton(nioshDialog)
        self.calcButton_2.setGeometry(QtCore.QRect(240, 370, 100, 30))
        self.calcButton_2.setStyleSheet("background-color: white;\n"
"color: black;")
        self.calcButton_2.setObjectName("calcButton_2")
        self.groupBox = QtWidgets.QGroupBox(nioshDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 341, 101))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.weightLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.weightLabel_2.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.weightLabel_2.setObjectName("weightLabel_2")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(140, 30, 181, 21))
        self.doubleSpinBox_6.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gripLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.gripLabel_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.gripLabel_2.setObjectName("gripLabel_2")
        self.gripBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.gripBox_2.setGeometry(QtCore.QRect(140, 60, 181, 21))
        self.gripBox_2.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(255, 255, 255);")
        self.gripBox_2.setMinimumContentsLength(3)
        self.gripBox_2.setObjectName("gripBox_2")
        self.gripBox_2.addItem("")
        self.gripBox_2.addItem("")
        self.gripBox_2.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(nioshDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 341, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.weightLabel_4 = QtWidgets.QLabel(self.groupBox_2)
        self.weightLabel_4.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.weightLabel_4.setObjectName("weightLabel_4")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(140, 30, 181, 21))
        self.doubleSpinBox_10.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.groupBox_3 = QtWidgets.QGroupBox(nioshDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 220, 341, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.weightLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.weightLabel_3.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.weightLabel_3.setObjectName("weightLabel_3")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(140, 30, 181, 21))
        self.doubleSpinBox_7.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gripLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.gripLabel_3.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.gripLabel_3.setObjectName("gripLabel_3")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(140, 60, 181, 21))
        self.doubleSpinBox_8.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(140, 90, 181, 21))
        self.doubleSpinBox_9.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gripLabel_4 = QtWidgets.QLabel(self.groupBox_3)
        self.gripLabel_4.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.gripLabel_4.setObjectName("gripLabel_4")

        self.retranslateUi(nioshDialog)
        QtCore.QMetaObject.connectSlotsByName(nioshDialog)

    def retranslateUi(self, nioshDialog):
        _translate = QtCore.QCoreApplication.translate
        nioshDialog.setWindowTitle(_translate("nioshDialog", "NIOSH Calculator"))
        self.calcButton.setText(_translate("nioshDialog", "Save"))
        self.calcButton_2.setText(_translate("nioshDialog", "Clear"))
        self.groupBox.setTitle(_translate("nioshDialog", "General"))
        self.weightLabel_2.setText(_translate("nioshDialog", "Object Weight"))
        self.gripLabel_2.setText(_translate("nioshDialog", "Grip Quality"))
        self.gripBox_2.setItemText(0, _translate("nioshDialog", "Good"))
        self.gripBox_2.setItemText(1, _translate("nioshDialog", "Fair"))
        self.gripBox_2.setItemText(2, _translate("nioshDialog", "Bad"))
        self.groupBox_2.setTitle(_translate("nioshDialog", "REBA Assessment"))
        self.weightLabel_4.setText(_translate("nioshDialog", "Frequency"))
        self.groupBox_3.setTitle(_translate("nioshDialog", "NIOSH Risk Index"))
        self.weightLabel_3.setText(_translate("nioshDialog", "Object Distance"))
        self.gripLabel_3.setText(_translate("nioshDialog", "Horizontal Distnance"))
        self.gripLabel_4.setText(_translate("nioshDialog", "Vertical Distance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nioshDialog = QtWidgets.QDialog()
    ui = Ui_nioshDialog()
    ui.setupUi(nioshDialog)
    nioshDialog.show()
    sys.exit(app.exec_())
