# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'niosh.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nioshDialog(object):
        def __init__(self, _source, _device, _model, _thres):
                self.source = _source
                self.device = _device
                self.model = _model
                self.thres = _thres

        def setupUi(self, nioshDialog):
                nioshDialog.setObjectName("nioshDialog")
                nioshDialog.resize(380, 409)
                nioshDialog.setAcceptDrops(False)
                nioshDialog.setAutoFillBackground(False)
                nioshDialog.setStyleSheet("background-color: rgb(44, 44, 44);\n"
        "color: #fff;")
                nioshDialog.setSizeGripEnabled(False)
                nioshDialog.setModal(False)
                self.saveButton = QtWidgets.QPushButton(nioshDialog)
                self.saveButton.setGeometry(QtCore.QRect(130, 370, 101, 30))
                self.saveButton.setStyleSheet("background-color: white;\n"
        "color: black;")
                self.saveButton.setObjectName("saveButton")
                self.clearButton = QtWidgets.QPushButton(nioshDialog)
                self.clearButton.setGeometry(QtCore.QRect(240, 370, 100, 30))
                self.clearButton.setStyleSheet("background-color: white;\n"
        "color: black;")
                self.clearButton.setObjectName("clearButton")
                self.groupBox = QtWidgets.QGroupBox(nioshDialog)
                self.groupBox.setGeometry(QtCore.QRect(20, 10, 341, 101))
                self.groupBox.setStyleSheet("")
                self.groupBox.setObjectName("groupBox")
                self.weightLabel = QtWidgets.QLabel(self.groupBox)
                self.weightLabel.setGeometry(QtCore.QRect(10, 30, 91, 20))
                self.weightLabel.setObjectName("weightLabel")
                self.weightBox = QtWidgets.QDoubleSpinBox(self.groupBox)
                self.weightBox.setGeometry(QtCore.QRect(140, 30, 181, 21))
                self.weightBox.setStyleSheet("border-color: rgb(44, 44, 44);")
                self.weightBox.setObjectName("weightBox")
                self.gripLabel = QtWidgets.QLabel(self.groupBox)
                self.gripLabel.setGeometry(QtCore.QRect(10, 60, 71, 16))
                self.gripLabel.setObjectName("gripLabel")
                self.gripBox = QtWidgets.QComboBox(self.groupBox)
                self.gripBox.setGeometry(QtCore.QRect(140, 60, 181, 21))
                self.gripBox.setStyleSheet("background-color: rgb(44, 44, 44);\n"
        "color: rgb(255, 255, 255);")
                self.gripBox.setMinimumContentsLength(3)
                self.gripBox.setObjectName("gripBox")
                self.gripBox.addItem("")
                self.gripBox.addItem("")
                self.gripBox.addItem("")
                self.groupBox_2 = QtWidgets.QGroupBox(nioshDialog)
                self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 341, 71))
                self.groupBox_2.setObjectName("groupBox_2")
                self.freqLabel = QtWidgets.QLabel(self.groupBox_2)
                self.freqLabel.setGeometry(QtCore.QRect(10, 30, 91, 20))
                self.freqLabel.setObjectName("freqLabel")
                self.freqBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
                self.freqBox.setGeometry(QtCore.QRect(140, 30, 181, 21))
                self.freqBox.setStyleSheet("border-color: rgb(44, 44, 44);")
                self.freqBox.setObjectName("freqBox")
                self.groupBox_3 = QtWidgets.QGroupBox(nioshDialog)
                self.groupBox_3.setGeometry(QtCore.QRect(20, 220, 341, 141))
                self.groupBox_3.setObjectName("groupBox_3")
                self.objDistLabel = QtWidgets.QLabel(self.groupBox_3)
                self.objDistLabel.setGeometry(QtCore.QRect(10, 30, 91, 20))
                self.objDistLabel.setObjectName("objDistLabel")
                self.objDistBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
                self.objDistBox.setGeometry(QtCore.QRect(140, 30, 181, 21))
                self.objDistBox.setStyleSheet("border-color: rgb(44, 44, 44);")
                self.objDistBox.setObjectName("objDistBox")
                self.hdLabel = QtWidgets.QLabel(self.groupBox_3)
                self.hdLabel.setGeometry(QtCore.QRect(10, 60, 121, 16))
                self.hdLabel.setObjectName("hdLabel")
                self.hDistanceBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
                self.hDistanceBox.setGeometry(QtCore.QRect(140, 60, 181, 21))
                self.hDistanceBox.setStyleSheet("border-color: rgb(44, 44, 44);")
                self.hDistanceBox.setObjectName("hDistanceBox")
                self.vDistanceBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
                self.vDistanceBox.setGeometry(QtCore.QRect(140, 90, 181, 21))
                self.vDistanceBox.setStyleSheet("border-color: rgb(44, 44, 44);")
                self.vDistanceBox.setObjectName("vDistanceBox")
                self.vdLabel = QtWidgets.QLabel(self.groupBox_3)
                self.vdLabel.setGeometry(QtCore.QRect(10, 90, 121, 16))
                self.vdLabel.setObjectName("vdLabel")

                self.retranslateUi(nioshDialog)
                QtCore.QMetaObject.connectSlotsByName(nioshDialog)

        def retranslateUi(self, nioshDialog):
                _translate = QtCore.QCoreApplication.translate
                nioshDialog.setWindowTitle(_translate("nioshDialog", "NIOSH Calculator"))
                self.saveButton.setText(_translate("nioshDialog", "Save"))
                self.clearButton.setText(_translate("nioshDialog", "Clear"))
                self.groupBox.setTitle(_translate("nioshDialog", "General"))
                self.weightLabel.setText(_translate("nioshDialog", "Object Weight"))
                self.gripLabel.setText(_translate("nioshDialog", "Grip Quality"))
                self.gripBox.setItemText(0, _translate("nioshDialog", "Good"))
                self.gripBox.setItemText(1, _translate("nioshDialog", "Fair"))
                self.gripBox.setItemText(2, _translate("nioshDialog", "Bad"))
                self.groupBox_2.setTitle(_translate("nioshDialog", "REBA Assessment"))
                self.freqLabel.setText(_translate("nioshDialog", "Frequency"))
                self.groupBox_3.setTitle(_translate("nioshDialog", "NIOSH Risk Index"))
                self.objDistLabel.setText(_translate("nioshDialog", "Object Distance"))
                self.hdLabel.setText(_translate("nioshDialog", "Horizontal Distnance"))
                self.vdLabel.setText(_translate("nioshDialog", "Vertical Distance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nioshDialog = QtWidgets.QDialog()
    ui = Ui_nioshDialog()
    ui.setupUi(nioshDialog)
    nioshDialog.show()
    sys.exit(app.exec_())
