# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(461, 294)
        settingsDialog.setStyleSheet("background-color: rgb(44, 44, 44); color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(settingsDialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(360, 30, 81, 161))
        self.buttonBox.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(44, 44, 44); border-color: rgba(255, 255, 255, 0);")
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(settingsDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 311, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(120, 30, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(settingsDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 120, 311, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(120, 30, 95, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(210, 30, 95, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.label = QtWidgets.QLabel(settingsDialog)
        self.label.setGeometry(QtCore.QRect(20, 230, 61, 16))
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(settingsDialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(90, 230, 241, 21))
        self.doubleSpinBox.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(44, 44, 44);")
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.retranslateUi(settingsDialog)
        self.buttonBox.accepted.connect(settingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(settingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Settings"))
        self.groupBox.setTitle(_translate("settingsDialog", "Device"))
        self.radioButton.setText(_translate("settingsDialog", "CPU"))
        self.radioButton_2.setText(_translate("settingsDialog", "GPU"))
        self.groupBox_2.setTitle(_translate("settingsDialog", "Model"))
        self.radioButton_5.setText(_translate("settingsDialog", "COCO"))
        self.radioButton_6.setText(_translate("settingsDialog", "MPI"))
        self.radioButton_7.setText(_translate("settingsDialog", "Body-25"))
        self.label.setText(_translate("settingsDialog", "Threshold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsDialog = QtWidgets.QDialog()
    ui = Ui_settingsDialog()
    ui.setupUi(settingsDialog)
    settingsDialog.show()
    sys.exit(app.exec_())
