# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#default value for skeletal extraction
source = 0
device = "cpu"
model = "BODY_25"
thres = 0.1

class Ui_settingsDialog(object):
        def getSource(self):
                return source
        def getDevice(self):
                return device
        def getModel(self):
                return model
        def getThreshold(self):
                return thres

        def setupUi(self, settingsDialog):
                settingsDialog.setObjectName("settingsDialog")
                settingsDialog.resize(461, 294)
                settingsDialog.setStyleSheet("background-color: rgb(44, 44, 44); color: rgb(255, 255, 255);")
                self.settingButton = QtWidgets.QDialogButtonBox(settingsDialog)
                self.settingButton.setEnabled(True)
                self.settingButton.setGeometry(QtCore.QRect(360, 30, 81, 161))
                self.settingButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(44, 44, 44); border-color: rgba(255, 255, 255, 0);")
                self.settingButton.setOrientation(QtCore.Qt.Vertical)
                self.settingButton.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
                self.settingButton.setObjectName("settingButton")
                self.deviceBox = QtWidgets.QGroupBox(settingsDialog)
                self.deviceBox.setGeometry(QtCore.QRect(20, 20, 311, 71))
                self.deviceBox.setObjectName("deviceBox")
                self.cpuOption = QtWidgets.QRadioButton(self.deviceBox)
                self.cpuOption.setGeometry(QtCore.QRect(20, 30, 95, 20))
                self.cpuOption.setObjectName("cpuOption")
                self.gpuOption = QtWidgets.QRadioButton(self.deviceBox)
                self.gpuOption.setGeometry(QtCore.QRect(120, 30, 95, 20))
                self.gpuOption.setObjectName("gpuOption")
                self.modelBox = QtWidgets.QGroupBox(settingsDialog)
                self.modelBox.setGeometry(QtCore.QRect(20, 120, 311, 71))
                self.modelBox.setObjectName("modelBox")
                self.cocoOption = QtWidgets.QRadioButton(self.modelBox)
                self.cocoOption.setGeometry(QtCore.QRect(20, 30, 95, 20))
                self.cocoOption.setObjectName("cocoOption")
                self.mpiOption = QtWidgets.QRadioButton(self.modelBox)
                self.mpiOption.setGeometry(QtCore.QRect(120, 30, 95, 20))
                self.mpiOption.setObjectName("mpiOption")
                self.body25Option = QtWidgets.QRadioButton(self.modelBox)
                self.body25Option.setGeometry(QtCore.QRect(210, 30, 95, 20))
                self.body25Option.setObjectName("body25Option")
                self.label = QtWidgets.QLabel(settingsDialog)
                self.label.setGeometry(QtCore.QRect(20, 240, 61, 16))
                self.label.setObjectName("label")
                self.thresholdBox = QtWidgets.QDoubleSpinBox(settingsDialog)
                self.thresholdBox.setGeometry(QtCore.QRect(90, 240, 241, 21))
                self.thresholdBox.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(44, 44, 44);")
                self.thresholdBox.setObjectName("thresholdBox")

                self.retranslateUi(settingsDialog)
                self.settingButton.accepted.connect(settingsDialog.accept) # type: ignore
                self.settingButton.rejected.connect(settingsDialog.reject) # type: ignore
                QtCore.QMetaObject.connectSlotsByName(settingsDialog)

        def retranslateUi(self, settingsDialog):
                _translate = QtCore.QCoreApplication.translate
                settingsDialog.setWindowTitle(_translate("settingsDialog", "Settings"))
                self.deviceBox.setTitle(_translate("settingsDialog", "Device"))
                self.cpuOption.setText(_translate("settingsDialog", "CPU"))
                self.gpuOption.setText(_translate("settingsDialog", "GPU"))
                self.modelBox.setTitle(_translate("settingsDialog", "Model"))
                self.cocoOption.setText(_translate("settingsDialog", "COCO"))
                self.mpiOption.setText(_translate("settingsDialog", "MPI"))
                self.body25Option.setText(_translate("settingsDialog", "Body-25"))
                self.label.setText(_translate("settingsDialog", "Threshold"))


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        settingsDialog = QtWidgets.QDialog()
        ui = Ui_settingsDialog()
        ui.setupUi(settingsDialog)
        settingsDialog.show()
        print(ui.getDevice())
        sys.exit(app.exec_())
