# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Niosh_graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 361)
        Form.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 30, 421, 251))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.weightLabel = QtWidgets.QLabel(self.groupBox_4)
        self.weightLabel.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.weightLabel.setObjectName("weightLabel")
        self.weightBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.weightBox.setGeometry(QtCore.QRect(150, 50, 121, 21))
        self.weightBox.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.weightBox.setObjectName("weightBox")
        self.weightUnit = QtWidgets.QComboBox(self.groupBox_4)
        self.weightUnit.setGeometry(QtCore.QRect(310, 50, 51, 22))
        self.weightUnit.setObjectName("weightUnit")
        self.weightUnit.addItem("")
        self.weightUnit.addItem("")
        self.objDistLabel = QtWidgets.QLabel(self.groupBox_4)
        self.objDistLabel.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.objDistLabel.setObjectName("objDistLabel")
        self.hdLabel = QtWidgets.QLabel(self.groupBox_4)
        self.hdLabel.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.hdLabel.setObjectName("hdLabel")
        self.vdLabel = QtWidgets.QLabel(self.groupBox_4)
        self.vdLabel.setGeometry(QtCore.QRect(10, 170, 121, 16))
        self.vdLabel.setObjectName("vdLabel")
        self.objDistBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.objDistBox.setGeometry(QtCore.QRect(150, 90, 121, 21))
        self.objDistBox.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.objDistBox.setObjectName("objDistBox")
        self.hdDistBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.hdDistBox.setGeometry(QtCore.QRect(150, 130, 121, 21))
        self.hdDistBox.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.hdDistBox.setObjectName("hdDistBox")
        self.vdDistBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.vdDistBox.setGeometry(QtCore.QRect(150, 170, 121, 21))
        self.vdDistBox.setStyleSheet("border-color: rgb(44, 44, 44);")
        self.vdDistBox.setObjectName("vdDistBox")
        self.objUnit = QtWidgets.QComboBox(self.groupBox_4)
        self.objUnit.setGeometry(QtCore.QRect(310, 90, 51, 22))
        self.objUnit.setObjectName("objUnit")
        self.objUnit.addItem("")
        self.objUnit.addItem("")
        self.hdUnit = QtWidgets.QComboBox(self.groupBox_4)
        self.hdUnit.setGeometry(QtCore.QRect(310, 130, 51, 22))
        self.hdUnit.setObjectName("hdUnit")
        self.hdUnit.addItem("")
        self.hdUnit.addItem("")
        self.weightUnit_5 = QtWidgets.QComboBox(self.groupBox_4)
        self.weightUnit_5.setGeometry(QtCore.QRect(310, 170, 51, 22))
        self.weightUnit_5.setObjectName("weightUnit_5")
        self.weightUnit_5.addItem("")
        self.weightUnit_5.addItem("")
        self.plot = QtWidgets.QPushButton(self.groupBox_4)
        self.plot.setGeometry(QtCore.QRect(80, 210, 241, 21))
        self.plot.setStyleSheet("background-color: white;\n"
"color: black;")
        self.plot.setObjectName("plot")
        self.graphWidget = PlotWidget(Form)
        self.graphWidget.setGeometry(QtCore.QRect(490, 40, 411, 281))
        self.graphWidget.setObjectName("graphWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_4.setTitle(_translate("Form", "General"))
        self.weightLabel.setText(_translate("Form", "Object Weight"))
        self.weightUnit.setItemText(0, _translate("Form", "lb"))
        self.weightUnit.setItemText(1, _translate("Form", "kg"))
        self.objDistLabel.setText(_translate("Form", "Object Distance"))
        self.hdLabel.setText(_translate("Form", "Horizontal Distnance"))
        self.vdLabel.setText(_translate("Form", "Vertical Distance"))
        self.objUnit.setItemText(0, _translate("Form", "lb"))
        self.objUnit.setItemText(1, _translate("Form", "kg"))
        self.hdUnit.setItemText(0, _translate("Form", "lb"))
        self.hdUnit.setItemText(1, _translate("Form", "kg"))
        self.weightUnit_5.setItemText(0, _translate("Form", "lb"))
        self.weightUnit_5.setItemText(1, _translate("Form", "kg"))
        self.plot.setText(_translate("Form", "Plot"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
